# Uncomment the next line to define a global platform for your project
# platform :ios, '11.2'

target 'Locket' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Locket
  pod 'Firebase/Core'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'

end
